import { 
  Employee, 
  AttendanceRecord, 
  LeaveRequest, 
  LeaveBalance, 
  Holiday, 
  Announcement, 
  AuditLog, 
  NotificationItem,
  SystemSettings 
} from '../types';

export const INITIAL_SETTINGS: SystemSettings = {
  companyName: 'Doctus Business Solutions',
  officialStartTime: '09:00',
  officialEndTime: '18:00',
  gracePeriodMinutes: 10,
  maxBreakMinutes: 60,
  workingDays: [1, 2, 3, 4, 5], // Mon-Fri
  alternateSaturdaysWorking: false,
  emailNotificationsEnabled: true,
  attendanceRemindersEnabled: true,
  // Production Attendance Control Settings
  autoPresentOnLogin: true,
  employeeCheckInEnabled: true,
  employeeCheckOutEnabled: true,
  employeeEditingEnabled: false, // Employees CANNOT edit attendance
  halfDayEnabled: true,
  tlManualAttendanceEnabled: true,
  managerManualAttendanceEnabled: true,
  hrManualAttendanceEnabled: true,
  adminManualAttendanceEnabled: true,
};

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    "id": "emp-seed-1",
    "employeeId": "DBS-25132",
    "firstName": "Siva",
    "lastName": "Naga Nikhil Krishna Kurra",
    "name": "Siva Naga Nikhil Krishna Kurra",
    "email": "dbs25132@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.625Z"
  },
  {
    "id": "emp-seed-2",
    "employeeId": "DBS-2519",
    "firstName": "Shiloni",
    "lastName": "Sastry Dunna",
    "name": "Shiloni Sastry Dunna",
    "email": "dbs2519@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-3",
    "employeeId": "DBS-2649",
    "firstName": "Durga",
    "lastName": "Sri Venkateswarlu Vemula",
    "name": "Durga Sri Venkateswarlu Vemula",
    "email": "dbs2649@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-4",
    "employeeId": "DBS-327",
    "firstName": "Vijaya",
    "lastName": "Sai Krishna Keerthi",
    "name": "Vijaya Sai Krishna Keerthi",
    "email": "dbs327@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-5",
    "employeeId": "DBS-230",
    "firstName": "Dharma",
    "lastName": "Teja Nama",
    "name": "Dharma Teja Nama",
    "email": "dbs230@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-6",
    "employeeId": "DBS-2511",
    "firstName": "Leela",
    "lastName": "Krishna Dasari",
    "name": "Leela Krishna Dasari",
    "email": "dbs2511@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-7",
    "employeeId": "DBS-424",
    "firstName": "Rakesh",
    "lastName": "Naragarla",
    "name": "Rakesh Naragarla",
    "email": "dbs424@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-8",
    "employeeId": "DBS-352",
    "firstName": "Vijaya",
    "lastName": "Bhaskar Devarapalli",
    "name": "Vijaya Bhaskar Devarapalli",
    "email": "dbs352@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-9",
    "employeeId": "DBS-2668",
    "firstName": "Emani",
    "lastName": "Rakesh",
    "name": "Emani Rakesh",
    "email": "dbs2668@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-10",
    "employeeId": "DBS-25159",
    "firstName": "Annavarapu",
    "lastName": "Abhishek",
    "name": "Annavarapu Abhishek",
    "email": "dbs25159@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-11",
    "employeeId": "DBS-548",
    "firstName": "Praneeth",
    "lastName": "Raj Bontha",
    "name": "Praneeth Raj Bontha",
    "email": "dbs548@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-12",
    "employeeId": "DBS-568",
    "firstName": "Venkata",
    "lastName": "Ramesh Polisetty",
    "name": "Venkata Ramesh Polisetty",
    "email": "dbs568@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-13",
    "employeeId": "DBS-549",
    "firstName": "Srinivas",
    "lastName": "Mannem",
    "name": "Srinivas Mannem",
    "email": "dbs549@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-14",
    "employeeId": "DBS-433",
    "firstName": "Satyanarayana",
    "lastName": "Reddy Akkala",
    "name": "Satyanarayana Reddy Akkala",
    "email": "dbs433@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-15",
    "employeeId": "DBS-2690",
    "firstName": "Nuthalapati",
    "lastName": "Karthik Teja",
    "name": "Nuthalapati Karthik Teja",
    "email": "dbs2690@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-16",
    "employeeId": "DBS-560",
    "firstName": "Anilkumar",
    "lastName": "Ullamgunta",
    "name": "Anilkumar Ullamgunta",
    "email": "dbs560@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-17",
    "employeeId": "DBS-2613",
    "firstName": "Naga",
    "lastName": "Sasidhar Reddy Akkala",
    "name": "Naga Sasidhar Reddy Akkala",
    "email": "dbs2613@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-18",
    "employeeId": "DBS-554",
    "firstName": "Purna",
    "lastName": "Venkata Krishna Sai Pattem",
    "name": "Purna Venkata Krishna Sai Pattem",
    "email": "dbs554@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-19",
    "employeeId": "DBS-2639",
    "firstName": "Shaik",
    "lastName": "Kutubuddin",
    "name": "Shaik Kutubuddin",
    "email": "dbs2639@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-20",
    "employeeId": "DBS-2514",
    "firstName": "Surendra",
    "lastName": "Kolatam",
    "name": "Surendra Kolatam",
    "email": "dbs2514@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-21",
    "employeeId": "DBS-2640",
    "firstName": "Lukka",
    "lastName": "Devendra",
    "name": "Lukka Devendra",
    "email": "dbs2640@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-22",
    "employeeId": "DBS-2685",
    "firstName": "Aradhyula",
    "lastName": "Sai Avinash Babu",
    "name": "Aradhyula Sai Avinash Babu",
    "email": "dbs2685@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-23",
    "employeeId": "DBS-2674",
    "firstName": "Mogalipuvvu",
    "lastName": "Ankamma Rao",
    "name": "Mogalipuvvu Ankamma Rao",
    "email": "dbs2674@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-24",
    "employeeId": "DBS-2555",
    "firstName": "Liveeju",
    "lastName": "Borugadda",
    "name": "Liveeju Borugadda",
    "email": "dbs2555@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-25",
    "employeeId": "DBS-2648",
    "firstName": "Aadi",
    "lastName": "Reddy Cheerala",
    "name": "Aadi Reddy Cheerala",
    "email": "dbs2648@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-26",
    "employeeId": "DBS-2669",
    "firstName": "Pamu",
    "lastName": "Nagendra Reddy",
    "name": "Pamu Nagendra Reddy",
    "email": "dbs2669@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-27",
    "employeeId": "DBS-2604",
    "firstName": "Gattu",
    "lastName": "Navakanth",
    "name": "Gattu Navakanth",
    "email": "dbs2604@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-28",
    "employeeId": "DBS-2605",
    "firstName": "Dividevara",
    "lastName": "Naga Babu",
    "name": "Dividevara Naga Babu",
    "email": "dbs2605@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-29",
    "employeeId": "DBS-512",
    "firstName": "Rafi",
    "lastName": "Mahammad",
    "name": "Rafi Mahammad",
    "email": "dbs512@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-30",
    "employeeId": "DBS-2616",
    "firstName": "Jaffer",
    "lastName": "Shaik",
    "name": "Jaffer Shaik",
    "email": "dbs2616@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-31",
    "employeeId": "DBS-2684",
    "firstName": "Shaik",
    "lastName": "Rehman Beig",
    "name": "Shaik Rehman Beig",
    "email": "dbs2684@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-32",
    "employeeId": "DBS-449",
    "firstName": "Jyothi",
    "lastName": "Swaroop Cheemakurti",
    "name": "Jyothi Swaroop Cheemakurti",
    "email": "dbs449@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-33",
    "employeeId": "DBS-466",
    "firstName": "Suresh",
    "lastName": "Dabbakuti",
    "name": "Suresh Dabbakuti",
    "email": "dbs466@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-34",
    "employeeId": "DBS-2606",
    "firstName": "Shaik",
    "lastName": "Jubear Ahammed",
    "name": "Shaik Jubear Ahammed",
    "email": "dbs2606@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-35",
    "employeeId": "DBS-2615",
    "firstName": "Mamilla",
    "lastName": "Sanjay",
    "name": "Mamilla Sanjay",
    "email": "dbs2615@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-36",
    "employeeId": "DBS-515",
    "firstName": "Mahaboob",
    "lastName": "Subhani Shaik",
    "name": "Mahaboob Subhani Shaik",
    "email": "dbs515@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-37",
    "employeeId": "DBS-25133",
    "firstName": "Mani",
    "lastName": "Varma Pusapati",
    "name": "Mani Varma Pusapati",
    "email": "dbs25133@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-38",
    "employeeId": "DBS-2686",
    "firstName": "Thatapudi",
    "lastName": "Anvesh Babu",
    "name": "Thatapudi Anvesh Babu",
    "email": "dbs2686@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-39",
    "employeeId": "DBS-2512",
    "firstName": "Bhavani",
    "lastName": "Shankar Kommuri",
    "name": "Bhavani Shankar Kommuri",
    "email": "dbs2512@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-40",
    "employeeId": "DBS-2554",
    "firstName": "Mohiddin",
    "lastName": "Mohammad",
    "name": "Mohiddin Mohammad",
    "email": "dbs2554@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-41",
    "employeeId": "DBS-513",
    "firstName": "Shahid",
    "lastName": "Shaik",
    "name": "Shahid Shaik",
    "email": "dbs513@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-42",
    "employeeId": "DBS-514",
    "firstName": "Zakeer",
    "lastName": "Hussain Mohammed",
    "name": "Zakeer Hussain Mohammed",
    "email": "dbs514@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-43",
    "employeeId": "DBS-25114",
    "firstName": "Syam",
    "lastName": "Venkata Sai Naralasetty",
    "name": "Syam Venkata Sai Naralasetty",
    "email": "dbs25114@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-44",
    "employeeId": "DBS-2607",
    "firstName": "Gollamudi",
    "lastName": "Yehoshuva",
    "name": "Gollamudi Yehoshuva",
    "email": "dbs2607@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-45",
    "employeeId": "DBS-429",
    "firstName": "Durgaprasad",
    "lastName": "Mandava",
    "name": "Durgaprasad Mandava",
    "email": "dbs429@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-46",
    "employeeId": "DBS-2530",
    "firstName": "Lalith",
    "lastName": "Venkata Sai Kota",
    "name": "Lalith Venkata Sai Kota",
    "email": "dbs2530@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-47",
    "employeeId": "DBS-511",
    "firstName": "Fhayaz",
    "lastName": "Ahammad Shaik",
    "name": "Fhayaz Ahammad Shaik",
    "email": "dbs511@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-48",
    "employeeId": "DBS-306",
    "firstName": "Rajesh",
    "lastName": "Dhabbakuti",
    "name": "Rajesh Dhabbakuti",
    "email": "dbs306@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-49",
    "employeeId": "DBS-2661",
    "firstName": "Pendyala",
    "lastName": "Venkata Ramesh",
    "name": "Pendyala Venkata Ramesh",
    "email": "dbs2661@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-50",
    "employeeId": "DBS-2617",
    "firstName": "Karthik",
    "lastName": "Dividevara",
    "name": "Karthik Dividevara",
    "email": "dbs2617@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-51",
    "employeeId": "DBS-540",
    "firstName": "Sagar",
    "lastName": "Alapati",
    "name": "Sagar Alapati",
    "email": "sagarlapati3695@gmail.com",
    "firebaseUid": "NWcCQo54XhPZUMu9C3AzppIZw802",
    "phone": "+91 98765 43210",
    "joiningDate": "2024-01-15",
    "designation": "System Administrator",
    "departmentId": "dept-admin",
    "departmentName": "Administration & HR",
    "teamId": "team-exec",
    "teamName": "Executive Leadership",
    "role": "admin",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-52",
    "employeeId": "DBS-25158",
    "firstName": "Atla",
    "lastName": "Naga Venu",
    "name": "Atla Naga Venu",
    "email": "dbs25158@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-53",
    "employeeId": "DBS-550",
    "firstName": "Prathyush",
    "lastName": "Raj Bontha",
    "name": "Prathyush Raj Bontha",
    "email": "dbs550@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-54",
    "employeeId": "DBS-25138",
    "firstName": "Surendra",
    "lastName": "Gudvalli",
    "name": "Surendra Gudvalli",
    "email": "dbs25138@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  },
  {
    "id": "emp-seed-55",
    "employeeId": "DBS-566",
    "firstName": "Vijay",
    "lastName": "Kumar Naligila",
    "name": "Vijay Kumar Naligila",
    "email": "dbs566@doctus.com",
    "firebaseUid": null,
    "phone": "-",
    "joiningDate": "2024-01-15",
    "designation": "AR Calling Specialist",
    "departmentId": "dept-ar",
    "departmentName": "AR Calling & Billing",
    "teamId": "team-ar-alpha",
    "teamName": "AR Calling Team Alpha",
    "role": "employee",
    "status": "ACTIVE",
    "photoURL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    "workLocation": "Hyderabad HQ",
    "employmentType": "Full-Time",
    "activatedAt": "2024-01-15T09:00:00Z",
    "createdAt": "2024-01-15T09:00:00Z",
    "updatedAt": "2026-09-15T20:56:03.626Z"
  }
];

export const INITIAL_LEAVE_BALANCES: Record<string, LeaveBalance> = {
  'EMP1001': {
    employeeId: 'EMP1001',
    casual: { total: 12, used: 4, available: 8 },
    sick: { total: 8, used: 2, available: 6 },
    earned: { total: 15, used: 3, available: 12 },
    unpaid: { used: 0 },
    wfh: { total: 24, used: 8, available: 16 }
  },
  'EMP1002': {
    employeeId: 'EMP1002',
    casual: { total: 12, used: 2, available: 10 },
    sick: { total: 8, used: 1, available: 7 },
    earned: { total: 15, used: 5, available: 10 },
    unpaid: { used: 0 },
    wfh: { total: 24, used: 5, available: 19 }
  },
  'EMP1003': {
    employeeId: 'EMP1003',
    casual: { total: 12, used: 5, available: 7 },
    sick: { total: 8, used: 3, available: 5 },
    earned: { total: 15, used: 0, available: 15 },
    unpaid: { used: 0 },
    wfh: { total: 24, used: 12, available: 12 }
  },
  'TL1001': {
    employeeId: 'TL1001',
    casual: { total: 12, used: 3, available: 9 },
    sick: { total: 8, used: 2, available: 6 },
    earned: { total: 15, used: 4, available: 11 },
    unpaid: { used: 0 },
    wfh: { total: 24, used: 6, available: 18 }
  }
};

export const INITIAL_HOLIDAYS: Holiday[] = [
  {
    id: 'hol-1',
    name: 'New Year Day',
    date: '2026-01-01',
    dayOfWeek: 'Thursday',
    type: 'PUBLIC',
    description: 'National Public Holiday'
  },
  {
    id: 'hol-2',
    name: 'Republic Day',
    date: '2026-01-26',
    dayOfWeek: 'Monday',
    type: 'PUBLIC',
    description: 'Indian Republic Day'
  },
  {
    id: 'hol-3',
    name: 'Holi',
    date: '2026-03-04',
    dayOfWeek: 'Wednesday',
    type: 'PUBLIC',
    description: 'Festival of Colors'
  },
  {
    id: 'hol-4',
    name: 'Independence Day',
    date: '2026-08-15',
    dayOfWeek: 'Saturday',
    type: 'PUBLIC',
    description: 'Indian Independence Day'
  },
  {
    id: 'hol-5',
    name: 'Gandhi Jayanti',
    date: '2026-10-02',
    dayOfWeek: 'Friday',
    type: 'PUBLIC',
    description: 'Mahatma Gandhi Birthday'
  },
  {
    id: 'hol-6',
    name: 'Diwali (Deepavali)',
    date: '2026-11-08',
    dayOfWeek: 'Sunday',
    type: 'PUBLIC',
    description: 'Festival of Lights'
  }
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Independence Day Holiday & Flag Hoisting Ceremony',
    message: 'Doctus Business Solutions will remain closed on August 15, 2026 for Independence Day. Join us virtually or at HQ for flag hoisting at 08:30 AM.',
    category: 'HOLIDAY',
    priority: 'HIGH',
    publishedBy: 'Priya Nair (HR)',
    publishedAt: '2026-08-12T10:00:00Z',
    startDate: '2026-08-12',
    endDate: '2026-08-16'
  },
  {
    id: 'ann-2',
    title: 'Updated Work From Home (WFH) & Check-In Grace Period Rules',
    message: 'Official office start time is 09:00 AM. A 10-minute grace period (up to 09:10 AM) is applicable. Check-ins after 09:10 AM will automatically record as LATE.',
    category: 'POLICY',
    priority: 'MEDIUM',
    publishedBy: 'Rajesh Sharma (Admin)',
    publishedAt: '2026-08-01T09:00:00Z',
    startDate: '2026-08-01',
    endDate: '2026-08-31'
  }
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'leave-101',
    employeeId: 'EMP1001',
    employeeName: 'Rahul Verma',
    employeeCode: 'EMP1001',
    departmentId: 'dept-ar',
    teamId: 'team-ar-alpha',
    leaveType: 'Casual Leave',
    fromDate: '2026-08-25',
    toDate: '2026-08-26',
    days: 2,
    reason: 'Family event and personal work in hometown.',
    contactDuringLeave: '+91 98765 43214',
    emergencyContact: '+91 98765 00000',
    status: 'PENDING_TL',
    tlId: 'emp-tl-1',
    approvalHistory: [],
    submittedAt: '2026-08-20T11:15:00Z',
    updatedAt: '2026-08-20T11:15:00Z'
  },
  {
    id: 'leave-102',
    employeeId: 'EMP1003',
    employeeName: 'Karthik Iyer',
    employeeCode: 'EMP1003',
    departmentId: 'dept-ar',
    teamId: 'team-ar-alpha',
    leaveType: 'Sick Leave',
    fromDate: '2026-08-18',
    toDate: '2026-08-18',
    days: 1,
    reason: 'High fever and doctor consultation.',
    contactDuringLeave: '+91 98765 43216',
    status: 'APPROVED',
    tlId: 'emp-tl-1',
    tlApproval: {
      role: 'tl',
      approverId: 'emp-tl-1',
      approverName: 'Ananya Deshmukh',
      action: 'APPROVED',
      comments: 'Take care & rest well.',
      timestamp: '2026-08-18T09:30:00Z'
    },
    approvalHistory: [
      {
        role: 'tl',
        approverId: 'emp-tl-1',
        approverName: 'Ananya Deshmukh',
        action: 'APPROVED',
        comments: 'Take care & rest well.',
        timestamp: '2026-08-18T09:30:00Z'
      }
    ],
    submittedAt: '2026-08-18T08:00:00Z',
    updatedAt: '2026-08-18T09:30:00Z'
  },
  {
    id: 'leave-103',
    employeeId: 'EMP1002',
    employeeName: 'Sneha Reddy',
    employeeCode: 'EMP1002',
    departmentId: 'dept-coding',
    teamId: 'team-coding-beta',
    leaveType: 'Earned Leave',
    fromDate: '2026-08-28',
    toDate: '2026-08-31',
    days: 4,
    reason: 'Outstation vacation planned in advance.',
    status: 'PENDING_TL',
    tlId: 'emp-tl-1',
    approvalHistory: [],
    submittedAt: '2026-08-19T14:20:00Z',
    updatedAt: '2026-08-19T14:20:00Z'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    timestamp: '2026-08-20T14:30:00Z',
    actorId: 'HR1001',
    actorName: 'Priya Nair',
    actorRole: 'hr',
    action: 'CREATE_EMPLOYEE',
    targetId: 'EMP1004',
    targetName: 'Meera Joshi',
    details: 'Created employee account for Meera Joshi (EMP1004) in AR Calling & Billing department. Secure invitation link dispatched.'
  },
  {
    id: 'audit-2',
    timestamp: '2026-08-18T09:30:00Z',
    actorId: 'TL1001',
    actorName: 'Ananya Deshmukh',
    actorRole: 'tl',
    action: 'APPROVE_LEAVE',
    targetId: 'leave-102',
    targetName: 'Karthik Iyer',
    details: 'Approved 1 day Sick Leave request for Karthik Iyer for date 2026-08-18.'
  }
];

// Helper function to generate realistic attendance data for August 2026 up to today (Aug 21)
export function generateSeedAttendance(): AttendanceRecord[] {
  const records: AttendanceRecord[] = [];
  const employees = [
    { id: 'EMP1001', name: 'Rahul Verma', dept: 'dept-ar', team: 'team-ar-alpha' },
    { id: 'EMP1002', name: 'Sneha Reddy', dept: 'dept-coding', team: 'team-coding-beta' },
    { id: 'EMP1003', name: 'Karthik Iyer', dept: 'dept-ar', team: 'team-ar-alpha' },
    { id: 'TL1001', name: 'Ananya Deshmukh', dept: 'dept-ar', team: 'team-ar-alpha' },
  ];

  // Loop through days 1 to 21 of August 2026
  for (let day = 1; day <= 21; day++) {
    const dateStr = `2026-08-${day < 10 ? '0' + day : day}`;
    const dateObj = new Date(2026, 7, day); // Month 7 is August
    const dayOfWeek = dateObj.getDay(); // 0 = Sun, 6 = Sat

    employees.forEach(emp => {
      // Check if it's today (Aug 21)
      const isToday = day === 21;

      if (dayOfWeek === 0 || dayOfWeek === 6) {
        // Week Off
        records.push({
          id: `att-${emp.id}-${dateStr}`,
          employeeId: emp.id,
          employeeName: emp.name,
          departmentId: emp.dept,
          teamId: emp.team,
          date: dateStr,
          status: 'WEEK_OFF',
          workMode: 'OFFICE',
          workingMinutes: 0,
          lateMinutes: 0,
          breakMinutes: 0,
          remarks: 'Weekend Off',
          createdAt: `${dateStr}T00:00:00Z`,
          updatedAt: `${dateStr}T00:00:00Z`
        });
      } else if (day === 15) {
        // Independence Day Holiday
        records.push({
          id: `att-${emp.id}-${dateStr}`,
          employeeId: emp.id,
          employeeName: emp.name,
          departmentId: emp.dept,
          teamId: emp.team,
          date: dateStr,
          status: 'HOLIDAY',
          workMode: 'OFFICE',
          workingMinutes: 0,
          lateMinutes: 0,
          breakMinutes: 0,
          remarks: 'Independence Day',
          createdAt: `${dateStr}T00:00:00Z`,
          updatedAt: `${dateStr}T00:00:00Z`
        });
      } else if (emp.id === 'EMP1003' && day === 18) {
        // Sick leave approved earlier
        records.push({
          id: `att-${emp.id}-${dateStr}`,
          employeeId: emp.id,
          employeeName: emp.name,
          departmentId: emp.dept,
          teamId: emp.team,
          date: dateStr,
          status: 'LEAVE',
          workMode: 'OFFICE',
          workingMinutes: 0,
          lateMinutes: 0,
          breakMinutes: 0,
          remarks: 'Sick Leave (Approved)',
          createdAt: `${dateStr}T00:00:00Z`,
          updatedAt: `${dateStr}T00:00:00Z`
        });
      } else if (isToday && emp.id === 'EMP1001') {
        // EMP1001 checked in today at 09:02 AM, currently checked in
        records.push({
          id: `att-${emp.id}-${dateStr}`,
          employeeId: emp.id,
          employeeName: emp.name,
          departmentId: emp.dept,
          teamId: emp.team,
          date: dateStr,
          checkIn: '09:02 AM',
          status: 'PRESENT',
          workMode: 'OFFICE',
          workingMinutes: 120, // 2 hours so far
          lateMinutes: 0,
          breakMinutes: 0,
          remarks: 'On Duty',
          createdAt: `${dateStr}T09:02:00Z`,
          updatedAt: `${dateStr}T09:02:00Z`
        });
      } else {
        // Regular working day
        // Slight variations (some late, some WFH)
        const isLate = (day % 7 === 2 && emp.id === 'EMP1003'); // Day 5, 12, 19
        const isWFH = (day % 5 === 0 && emp.id === 'EMP1002');

        const checkInTime = isLate ? '09:18 AM' : '08:58 AM';
        const checkOutTime = '06:05 PM';
        const lateMins = isLate ? 18 : 0;
        const status = isLate ? 'LATE' : (isWFH ? 'WFH' : 'PRESENT');

        records.push({
          id: `att-${emp.id}-${dateStr}`,
          employeeId: emp.id,
          employeeName: emp.name,
          departmentId: emp.dept,
          teamId: emp.team,
          date: dateStr,
          checkIn: checkInTime,
          checkOut: checkOutTime,
          workingMinutes: 545, // 9 hours 5 minutes
          status: status,
          workMode: isWFH ? 'WFH' : 'OFFICE',
          attendanceSource: isLate ? 'LOGIN' : (isWFH ? 'WFH' : 'EMPLOYEE_CHECK_IN'),
          lateMinutes: lateMins,
          breakMinutes: 45,
          remarks: isLate ? 'Checked in after 09:10 AM grace period' : 'Regular Shift',
          createdAt: `${dateStr}T${checkInTime}`,
          updatedAt: `${dateStr}T${checkOutTime}`
        });
      }
    });
  }

  return records;
}
